import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useActiveWeb3React from '../hooks/web3/useActiveWeb3React'
import { AbstractConnector } from '@web3-react/abstract-connector'
import { UnsupportedChainIdError } from '@web3-react/core'
import { injectedConnector } from '../connectors'

const Home: NextPage = () => {
  const { activate, account } = useActiveWeb3React()
  console.log(account)

  // Used for wallet connection.
  const tryActivation = async (connector: AbstractConnector | undefined) => {        
    connector && activate(connector, undefined, true).catch(async (error) => {
        if (error instanceof UnsupportedChainIdError) {
            alert('Unsupported Network')
        }
    })
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello Web3!
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <p className={styles.description}>
          Or try out wallet connection below:
        </p>

        <span className={styles.description}>Your address: {account ? account : "NOT CONNECTED"}</span>
        {!account && <button onClick={() => tryActivation(injectedConnector)}>
          Connect Wallet
        </button>}
      </main>
    </div>
  )
}

export default Home
